-- =============================================================================
-- PHASE 2: File Formats and Stages
-- =============================================================================

USE SCHEMA SUPPLY_CHAIN_HUB.SC_STAGES;

CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE='CSV' SKIP_HEADER=1 FIELD_DELIMITER=',' FIELD_OPTIONALLY_ENCLOSED_BY='"'
  TRIM_SPACE=TRUE NULL_IF=('','NULL','null')
  ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE MULTI_LINE=TRUE;

CREATE OR REPLACE FILE FORMAT FF_JSON
  TYPE='JSON' STRIP_OUTER_ARRAY=TRUE MULTI_LINE=TRUE;

CREATE OR REPLACE FILE FORMAT FF_PARQUET
  TYPE='PARQUET' COMPRESSION='SNAPPY';

CREATE OR REPLACE FILE FORMAT FF_VARIANT
  TYPE='JSON' STRIP_OUTER_ARRAY=FALSE MULTI_LINE=TRUE;

CREATE OR REPLACE STAGE STG_ERP DIRECTORY=(ENABLE=TRUE);
CREATE OR REPLACE STAGE STG_SUPPLIER DIRECTORY=(ENABLE=TRUE);
CREATE OR REPLACE STAGE STG_FREIGHT DIRECTORY=(ENABLE=TRUE);
CREATE OR REPLACE STAGE STG_PLANT DIRECTORY=(ENABLE=TRUE);
CREATE OR REPLACE STAGE STG_FINANCE DIRECTORY=(ENABLE=TRUE);
CREATE OR REPLACE STAGE STG_SEMANTIC_MODELS;

USE SCHEMA SUPPLY_CHAIN_HUB.SC_APP;
CREATE OR REPLACE STAGE STG_STREAMLIT;
