-- =============================================================================
-- PHASE 3: Raw Tables (16 tables)
-- =============================================================================

USE SCHEMA SUPPLY_CHAIN_HUB.SC_RAW;

CREATE OR REPLACE TABLE ERP_SALES_ORDERS (
  ORDER_NBR VARCHAR(10), PLANT_CODE VARCHAR(4), CUST_NBR VARCHAR(8),
  ORDER_DATE NUMBER(38,0), PROMISED_DATE NUMBER(38,0), ORDER_STATUS VARCHAR(2),
  ORDER_TOTAL_USD NUMBER(12,2), SALES_ORG VARCHAR(4), DIST_CHANNEL VARCHAR(2),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE ERP_ORDER_LINES (
  ORDER_NBR VARCHAR(10), LINE_NBR NUMBER(38,0), MATERIAL_NBR VARCHAR(18),
  QUANTITY_ORDERED NUMBER(10,3), QUANTITY_DELIVERED NUMBER(10,3), UOM VARCHAR(3),
  UNIT_PRICE_USD NUMBER(10,4), LINE_STATUS VARCHAR(2), PROMISED_DATE NUMBER(38,0),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE ERP_INVENTORY_SNAPSHOTS (
  SNAPSHOT_DATE NUMBER(38,0), PLANT_CODE VARCHAR(4), MATERIAL_NBR VARCHAR(18),
  QTY_ON_HAND NUMBER(12,3), QTY_IN_TRANSIT NUMBER(12,3), QTY_RESERVED NUMBER(12,3),
  UOM VARCHAR(3), VALUATION_USD NUMBER(14,2),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE ERP_MATERIAL_MASTER (
  MATERIAL_NBR VARCHAR(18), MATERIAL_DESC VARCHAR(100), MATERIAL_TYPE VARCHAR(4),
  MATERIAL_GROUP VARCHAR(10), BASE_UOM VARCHAR(3), GROSS_WEIGHT NUMBER(8,3),
  WEIGHT_UNIT VARCHAR(3), STANDARD_COST NUMBER(10,4),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE ERP_PLANT_MASTER (
  PLANT_CODE VARCHAR(4), PLANT_NAME VARCHAR(100), COUNTRY_CODE VARCHAR(2),
  REGION VARCHAR(20), CITY VARCHAR(50), PLANT_TYPE VARCHAR(20),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE SUP_SUPPLIERS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE SUP_PURCHASE_ORDERS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE SUP_RECEIPTS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE TMS_SHIPMENTS_MASTER (
  SHIPMENT_ID VARCHAR(15), ORDER_REF VARCHAR(10), CARRIER_ID VARCHAR(10),
  ORIGIN_FACILITY VARCHAR(100), DESTINATION VARCHAR(200),
  SHIP_DATE VARCHAR(10), PROMISED_DELIVERY VARCHAR(10), ACTUAL_DELIVERY VARCHAR(10),
  WEIGHT_KGS NUMBER(10,2), PIECES NUMBER(38,0), STATUS VARCHAR(20), DAMAGE_FLAG VARCHAR(1),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE TMS_CARRIER_MASTER (
  CARRIER_ID VARCHAR(10), CARRIER_NAME VARCHAR(100), CARRIER_TYPE VARCHAR(20),
  COUNTRY_BASE VARCHAR(2), REGION_COVERAGE VARCHAR(50), RELIABILITY_SCORE NUMBER(3,2),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE TMS_SHIPMENT_EVENTS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE IOT_SENSOR_READINGS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE IOT_QUALITY_EVENTS (
  RAW_PAYLOAD VARIANT,
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE FIN_COST_ALLOCATIONS (
  ALLOCATION_ID VARCHAR(20), VENDOR_CODE VARCHAR(10), COST_CENTER_ID VARCHAR(10),
  MATERIAL_NBR VARCHAR(18), COST_TYPE VARCHAR(20), AMOUNT NUMBER(12,4),
  FROM_CURRENCY VARCHAR(3), TO_CURRENCY VARCHAR(3), EXCHANGE_RATE NUMBER(10,6),
  AMOUNT_USD NUMBER(12,4), EFFECTIVE_DATE VARCHAR(10), SHIPMENT_REF VARCHAR(15),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE FIN_EXCHANGE_RATES (
  RATE_DATE VARCHAR(10), FROM_CURRENCY VARCHAR(3), TO_CURRENCY VARCHAR(3),
  EXCHANGE_RATE NUMBER(10,6), SOURCE VARCHAR(20),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);

CREATE OR REPLACE TABLE FIN_TARIFFS (
  TARIFF_CODE VARCHAR(10), DESCRIPTION VARCHAR(200), DUTY_RATE_PCT NUMBER(5,2),
  ORIGIN_COUNTRY VARCHAR(2), DESTINATION_COUNTRY VARCHAR(2),
  EFFECTIVE_FROM VARCHAR(10), EFFECTIVE_TO VARCHAR(10),
  _LOAD_BATCH_ID VARCHAR(50), _LOADED_AT TIMESTAMP_NTZ(9),
  _SOURCE_FILE VARCHAR(500), _SOURCE_ROW_NUMBER NUMBER(38,0)
);
