-- =============================================================================
-- PHASE 5: COPY INTO Raw Tables
-- IMPORTANT: Parquet uses UPPERCASE field names ($1:SNAPSHOT_DATE)
-- =============================================================================

USE SCHEMA SUPPLY_CHAIN_HUB.SC_RAW;

SET batch_id = 'deploy-' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD-HH24MISS');

COPY INTO ERP_SALES_ORDERS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/orders/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO ERP_ORDER_LINES FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/order_lines/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO ERP_INVENTORY_SNAPSHOTS FROM (
  SELECT $1:SNAPSHOT_DATE::NUMBER, $1:PLANT_CODE::VARCHAR, $1:MATERIAL_NBR::VARCHAR,
    $1:QTY_ON_HAND::NUMBER, $1:QTY_IN_TRANSIT::NUMBER, $1:QTY_RESERVED::NUMBER,
    $1:UOM::VARCHAR, $1:VALUATION_USD::NUMBER,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/inventory/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_PARQUET') ON_ERROR='ABORT_STATEMENT';

COPY INTO ERP_MATERIAL_MASTER FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/materials/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO ERP_PLANT_MASTER FROM (
  SELECT $1,$2,$3,$4,$5,$6,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/plants/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO SUP_SUPPLIERS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_SUPPLIER/suppliers/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_JSON') ON_ERROR='ABORT_STATEMENT';

COPY INTO SUP_PURCHASE_ORDERS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_SUPPLIER/purchase_orders/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_JSON') ON_ERROR='ABORT_STATEMENT';

COPY INTO SUP_RECEIPTS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_SUPPLIER/receipts/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_JSON') ON_ERROR='ABORT_STATEMENT';

COPY INTO TMS_SHIPMENTS_MASTER FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FREIGHT/shipments_master/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO TMS_CARRIER_MASTER FROM (
  SELECT $1,$2,$3,$4,$5,$6,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FREIGHT/carrier_master/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO TMS_SHIPMENT_EVENTS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FREIGHT/events/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_JSON') ON_ERROR='ABORT_STATEMENT';

COPY INTO IOT_SENSOR_READINGS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_PLANT/sensor_readings/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_VARIANT') ON_ERROR='ABORT_STATEMENT';

COPY INTO IOT_QUALITY_EVENTS FROM (
  SELECT $1,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_PLANT/quality_events/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_VARIANT') ON_ERROR='ABORT_STATEMENT';

COPY INTO FIN_COST_ALLOCATIONS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FINANCE/cost_allocations/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO FIN_EXCHANGE_RATES FROM (
  SELECT $1,$2,$3,$4,$5,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FINANCE/exchange_rates/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

COPY INTO FIN_TARIFFS FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,
    $batch_id, CURRENT_TIMESTAMP(), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_FINANCE/tariffs/
) FILE_FORMAT=(FORMAT_NAME='SUPPLY_CHAIN_HUB.SC_STAGES.FF_CSV') ON_ERROR='ABORT_STATEMENT';

-- =============================================================================
-- VALIDATE RAW COUNTS (all must match)
-- =============================================================================
SELECT 'ERP_SALES_ORDERS' AS TBL, COUNT(*) AS CNT, 10000 AS EXPECTED FROM ERP_SALES_ORDERS
UNION ALL SELECT 'ERP_ORDER_LINES', COUNT(*), 20000 FROM ERP_ORDER_LINES
UNION ALL SELECT 'ERP_INVENTORY_SNAPSHOTS', COUNT(*), 16443 FROM ERP_INVENTORY_SNAPSHOTS
UNION ALL SELECT 'ERP_MATERIAL_MASTER', COUNT(*), 500 FROM ERP_MATERIAL_MASTER
UNION ALL SELECT 'ERP_PLANT_MASTER', COUNT(*), 20 FROM ERP_PLANT_MASTER
UNION ALL SELECT 'SUP_SUPPLIERS', COUNT(*), 100 FROM SUP_SUPPLIERS
UNION ALL SELECT 'SUP_PURCHASE_ORDERS', COUNT(*), 8000 FROM SUP_PURCHASE_ORDERS
UNION ALL SELECT 'SUP_RECEIPTS', COUNT(*), 6403 FROM SUP_RECEIPTS
UNION ALL SELECT 'TMS_SHIPMENTS_MASTER', COUNT(*), 10501 FROM TMS_SHIPMENTS_MASTER
UNION ALL SELECT 'TMS_CARRIER_MASTER', COUNT(*), 15 FROM TMS_CARRIER_MASTER
UNION ALL SELECT 'TMS_SHIPMENT_EVENTS', COUNT(*), 30465 FROM TMS_SHIPMENT_EVENTS
UNION ALL SELECT 'IOT_SENSOR_READINGS', COUNT(*), 40000 FROM IOT_SENSOR_READINGS
UNION ALL SELECT 'IOT_QUALITY_EVENTS', COUNT(*), 5000 FROM IOT_QUALITY_EVENTS
UNION ALL SELECT 'FIN_COST_ALLOCATIONS', COUNT(*), 5000 FROM FIN_COST_ALLOCATIONS
UNION ALL SELECT 'FIN_EXCHANGE_RATES', COUNT(*), 2520 FROM FIN_EXCHANGE_RATES
UNION ALL SELECT 'FIN_TARIFFS', COUNT(*), 200 FROM FIN_TARIFFS
ORDER BY TBL;
