-- =============================================================================
-- PHASE 6: XREF Identity Resolution Tables
-- =============================================================================

USE SCHEMA SUPPLY_CHAIN_HUB.SC_CURATED;

CREATE OR REPLACE TABLE XREF_SUPPLIER (
  CANONICAL_SUPPLIER_ID NUMBER(38,0) NOT NULL,
  ERP_VENDOR_CODE VARCHAR(10) NOT NULL,
  SUPPLIERNET_UUID VARCHAR(50) NOT NULL,
  COMPANY_NAME VARCHAR(100),
  CONSTRAINT PK_XREF_SUPPLIER PRIMARY KEY (CANONICAL_SUPPLIER_ID)
) COMMENT='Cross-reference: SupplierNet UUID to ERP VENDOR_CODE. 100 suppliers.';

CREATE OR REPLACE TABLE XREF_PART (
  CANONICAL_PART_ID NUMBER(38,0) NOT NULL,
  ERP_MATERIAL_NBR VARCHAR(18) NOT NULL,
  SUPPLIERNET_PART_NUMBER VARCHAR(20) NOT NULL,
  CONSTRAINT PK_XREF_PART PRIMARY KEY (CANONICAL_PART_ID)
) COMMENT='Cross-reference: SupplierNet part to ERP MATERIAL_NBR. 500 parts.';

CREATE OR REPLACE TABLE XREF_PLANT (
  CANONICAL_PLANT_ID NUMBER(38,0) NOT NULL,
  ERP_PLANT_CODE VARCHAR(4) NOT NULL,
  FREIGHTLINK_FACILITY_NAME VARCHAR(100) NOT NULL,
  IOT_PLANT_CODE VARCHAR(4) NOT NULL,
  PLANT_NAME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_XREF_PLANT PRIMARY KEY (CANONICAL_PLANT_ID)
) COMMENT='Cross-reference: FreightLink facility to ERP PLANT_CODE. 20 plants.';

-- Load XREF from JSON identity map
INSERT INTO XREF_SUPPLIER (CANONICAL_SUPPLIER_ID, ERP_VENDOR_CODE, SUPPLIERNET_UUID, COMPANY_NAME)
SELECT f.value:canonical_id::NUMBER, f.value:erp_vendor_code::VARCHAR,
       f.value:suppliernet_uuid::VARCHAR, f.value:company_name::VARCHAR
FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/xref/_xref_identity_map.json
     (FILE_FORMAT => 'SUPPLY_CHAIN_HUB.SC_STAGES.FF_VARIANT') t,
     LATERAL FLATTEN(input => t.$1:suppliers) f;

INSERT INTO XREF_PART (CANONICAL_PART_ID, ERP_MATERIAL_NBR, SUPPLIERNET_PART_NUMBER)
SELECT f.value:canonical_id::NUMBER, f.value:erp_material_nbr::VARCHAR,
       f.value:suppliernet_part_number::VARCHAR
FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/xref/_xref_identity_map.json
     (FILE_FORMAT => 'SUPPLY_CHAIN_HUB.SC_STAGES.FF_VARIANT') t,
     LATERAL FLATTEN(input => t.$1:parts) f;

INSERT INTO XREF_PLANT (CANONICAL_PLANT_ID, ERP_PLANT_CODE, FREIGHTLINK_FACILITY_NAME, IOT_PLANT_CODE, PLANT_NAME)
SELECT f.value:canonical_id::NUMBER, f.value:erp_plant_code::VARCHAR,
       f.value:freightlink_facility_name::VARCHAR, f.value:iot_plant_code::VARCHAR,
       f.value:plant_name::VARCHAR
FROM @SUPPLY_CHAIN_HUB.SC_STAGES.STG_ERP/xref/_xref_identity_map.json
     (FILE_FORMAT => 'SUPPLY_CHAIN_HUB.SC_STAGES.FF_VARIANT') t,
     LATERAL FLATTEN(input => t.$1:plants) f;

-- VALIDATE: XREF_SUPPLIER=100, XREF_PART=500, XREF_PLANT=20
SELECT 'XREF_SUPPLIER' AS TBL, COUNT(*) AS CNT, 100 AS EXPECTED FROM XREF_SUPPLIER
UNION ALL SELECT 'XREF_PART', COUNT(*), 500 FROM XREF_PART
UNION ALL SELECT 'XREF_PLANT', COUNT(*), 20 FROM XREF_PLANT;
