-- =============================================================================
-- PHASE 11: Governance Tables
-- =============================================================================

USE SCHEMA SUPPLY_CHAIN_HUB.SC_GOV;

CREATE OR REPLACE TABLE PROJECT_METADATA (
  CONFIG_KEY VARCHAR(100) NOT NULL,
  CONFIG_VALUE VARCHAR(2000) NOT NULL,
  DESCRIPTION VARCHAR(500),
  UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PROJECT_META PRIMARY KEY (CONFIG_KEY)
) COMMENT='Project-level configuration and metadata';

CREATE OR REPLACE TABLE SOURCE_SYSTEM_REGISTRY (
  SOURCE_SYSTEM_ID VARCHAR(20) NOT NULL,
  SOURCE_SYSTEM_NAME VARCHAR(100) NOT NULL,
  VENDOR_LABEL VARCHAR(100) NOT NULL,
  BUSINESS_DOMAIN VARCHAR(50) NOT NULL,
  SOURCE_FORMAT VARCHAR(20) NOT NULL,
  REFRESH_PATTERN VARCHAR(100) NOT NULL,
  STAGE_NAME VARCHAR(100),
  SOURCE_SCHEMA_DESC VARCHAR(2000),
  ID_CONVENTIONS VARCHAR(1000),
  DATE_FORMAT VARCHAR(100),
  CURRENCY_HANDLING VARCHAR(200),
  UOM_CONVENTION VARCHAR(200),
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SOURCE_SYSTEM PRIMARY KEY (SOURCE_SYSTEM_ID)
) COMMENT='Registry of all source vendor systems';

CREATE OR REPLACE TABLE OBJECT_INVENTORY (
  OBJECT_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  CHECKPOINT VARCHAR(10) NOT NULL,
  OBJECT_TYPE VARCHAR(30) NOT NULL,
  FULLY_QUALIFIED_NAME VARCHAR(300) NOT NULL,
  SCHEMA_NAME VARCHAR(100),
  PURPOSE VARCHAR(500),
  DEPENDS_ON VARCHAR(500),
  CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY VARCHAR(50) DEFAULT CURRENT_USER(),
  STATUS VARCHAR(20) DEFAULT 'ACTIVE',
  CONSTRAINT PK_OBJ_INV PRIMARY KEY (OBJECT_ID)
) COMMENT='Project object inventory - tracks all objects created across checkpoints';

CREATE OR REPLACE TABLE RAW_INGESTION_AUDIT (
  AUDIT_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  BATCH_ID VARCHAR(50) NOT NULL,
  SOURCE_SYSTEM VARCHAR(20) NOT NULL,
  STAGE_NAME VARCHAR(50) NOT NULL,
  SOURCE_FILE_PATH VARCHAR(200) NOT NULL,
  TARGET_TABLE VARCHAR(100) NOT NULL,
  STARTED_AT TIMESTAMP_NTZ(9) NOT NULL,
  COMPLETED_AT TIMESTAMP_NTZ(9),
  STATUS VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
  ROWS_LOADED NUMBER(38,0),
  FILE_SIZE_BYTES NUMBER(38,0),
  ERROR_MESSAGE VARCHAR(2000),
  CONSTRAINT PK_AUDIT PRIMARY KEY (AUDIT_ID)
) COMMENT='Batch-level ingestion audit log';

CREATE OR REPLACE TABLE ACTION_AUDIT (
  ACTION_ID VARCHAR(50) NOT NULL,
  ACTION_TYPE VARCHAR(20) NOT NULL,
  ACTION_STATUS VARCHAR(20) NOT NULL,
  KPI_CONTEXT VARCHAR(20),
  PAYLOAD_SUMMARY VARCHAR(1000),
  PAYLOAD_HASH VARCHAR(64),
  TARGET_ENDPOINT VARCHAR(200),
  USER_CONFIRMED BOOLEAN DEFAULT FALSE,
  USER_CONFIRMED_AT TIMESTAMP_NTZ(9),
  EXECUTED_AT TIMESTAMP_NTZ(9),
  RESPONSE_CODE NUMBER(38,0),
  ERROR_MESSAGE VARCHAR(500),
  RETRY_COUNT NUMBER(38,0) DEFAULT 0,
  SESSION_ID VARCHAR(100),
  CREATED_BY VARCHAR(50) DEFAULT CURRENT_USER(),
  CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ACTION_ID)
) COMMENT='Audit log for all external actions (Jira, SMS, WhatsApp)';
