-- =============================================================================
-- PHASE 12: RBAC
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE SC_HACKATHON_ADMIN    COMMENT='Supply Chain Hackathon - Project admin role';
CREATE OR REPLACE ROLE SC_HACKATHON_DEVELOPER COMMENT='Supply Chain Hackathon - Developer role';
CREATE OR REPLACE ROLE SC_HACKATHON_ANALYST   COMMENT='Supply Chain Hackathon - Analyst role. Read-only semantic/ontology.';
CREATE OR REPLACE ROLE SC_HACKATHON_OPERATOR  COMMENT='Supply Chain Hackathon - Operator role. Actions + monitoring.';

-- Role hierarchy
GRANT ROLE SC_HACKATHON_DEVELOPER TO ROLE SC_HACKATHON_ADMIN;
GRANT ROLE SC_HACKATHON_ANALYST   TO ROLE SC_HACKATHON_ADMIN;
GRANT ROLE SC_HACKATHON_OPERATOR  TO ROLE SC_HACKATHON_ADMIN;
GRANT ROLE SC_HACKATHON_ADMIN     TO ROLE ACCOUNTADMIN;

-- Database usage
GRANT USAGE ON DATABASE SUPPLY_CHAIN_HUB TO ROLE SC_HACKATHON_ADMIN;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_HUB TO ROLE SC_HACKATHON_ANALYST;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_HUB TO ROLE SC_HACKATHON_OPERATOR;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_HUB TO ROLE SC_HACKATHON_DEVELOPER;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_HACKATHON_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_HACKATHON_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_HACKATHON_OPERATOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_HACKATHON_DEVELOPER;

-- Analyst: read-only on semantic + ontology + governance + app
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_HUB.SC_SEM TO ROLE SC_HACKATHON_ANALYST;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_HUB.SC_ONT TO ROLE SC_HACKATHON_ANALYST;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_HUB.SC_GOV TO ROLE SC_HACKATHON_ANALYST;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_HUB.SC_APP TO ROLE SC_HACKATHON_ANALYST;

GRANT SELECT ON ALL VIEWS  IN SCHEMA SUPPLY_CHAIN_HUB.SC_SEM TO ROLE SC_HACKATHON_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA SUPPLY_CHAIN_HUB.SC_ONT TO ROLE SC_HACKATHON_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_HUB.SC_ONT TO ROLE SC_HACKATHON_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLY_CHAIN_HUB.SC_GOV TO ROLE SC_HACKATHON_ANALYST;

-- Operator: governance + action audit insert
GRANT USAGE  ON SCHEMA SUPPLY_CHAIN_HUB.SC_GOV TO ROLE SC_HACKATHON_OPERATOR;
GRANT INSERT ON TABLE  SUPPLY_CHAIN_HUB.SC_GOV.ACTION_AUDIT TO ROLE SC_HACKATHON_OPERATOR;
