-- =============================================================================
-- FINAL VALIDATION
-- Run after all data is loaded to verify KPI values
-- =============================================================================

-- Raw table counts
SELECT 'ERP_SALES_ORDERS' AS TBL, COUNT(*) AS CNT, 10000 AS EXPECTED FROM SUPPLY_CHAIN_HUB.SC_RAW.ERP_SALES_ORDERS
UNION ALL SELECT 'ERP_ORDER_LINES', COUNT(*), 20000 FROM SUPPLY_CHAIN_HUB.SC_RAW.ERP_ORDER_LINES
UNION ALL SELECT 'ERP_INVENTORY_SNAPSHOTS', COUNT(*), 16443 FROM SUPPLY_CHAIN_HUB.SC_RAW.ERP_INVENTORY_SNAPSHOTS
UNION ALL SELECT 'ERP_MATERIAL_MASTER', COUNT(*), 500 FROM SUPPLY_CHAIN_HUB.SC_RAW.ERP_MATERIAL_MASTER
UNION ALL SELECT 'ERP_PLANT_MASTER', COUNT(*), 20 FROM SUPPLY_CHAIN_HUB.SC_RAW.ERP_PLANT_MASTER
UNION ALL SELECT 'SUP_SUPPLIERS', COUNT(*), 100 FROM SUPPLY_CHAIN_HUB.SC_RAW.SUP_SUPPLIERS
UNION ALL SELECT 'SUP_PURCHASE_ORDERS', COUNT(*), 8000 FROM SUPPLY_CHAIN_HUB.SC_RAW.SUP_PURCHASE_ORDERS
UNION ALL SELECT 'SUP_RECEIPTS', COUNT(*), 6403 FROM SUPPLY_CHAIN_HUB.SC_RAW.SUP_RECEIPTS
UNION ALL SELECT 'TMS_SHIPMENTS_MASTER', COUNT(*), 10501 FROM SUPPLY_CHAIN_HUB.SC_RAW.TMS_SHIPMENTS_MASTER
UNION ALL SELECT 'TMS_CARRIER_MASTER', COUNT(*), 15 FROM SUPPLY_CHAIN_HUB.SC_RAW.TMS_CARRIER_MASTER
UNION ALL SELECT 'TMS_SHIPMENT_EVENTS', COUNT(*), 30465 FROM SUPPLY_CHAIN_HUB.SC_RAW.TMS_SHIPMENT_EVENTS
UNION ALL SELECT 'IOT_SENSOR_READINGS', COUNT(*), 40000 FROM SUPPLY_CHAIN_HUB.SC_RAW.IOT_SENSOR_READINGS
UNION ALL SELECT 'IOT_QUALITY_EVENTS', COUNT(*), 5000 FROM SUPPLY_CHAIN_HUB.SC_RAW.IOT_QUALITY_EVENTS
UNION ALL SELECT 'FIN_COST_ALLOCATIONS', COUNT(*), 5000 FROM SUPPLY_CHAIN_HUB.SC_RAW.FIN_COST_ALLOCATIONS
UNION ALL SELECT 'FIN_EXCHANGE_RATES', COUNT(*), 2520 FROM SUPPLY_CHAIN_HUB.SC_RAW.FIN_EXCHANGE_RATES
UNION ALL SELECT 'FIN_TARIFFS', COUNT(*), 200 FROM SUPPLY_CHAIN_HUB.SC_RAW.FIN_TARIFFS
ORDER BY TBL;

-- XREF counts
SELECT 'XREF_SUPPLIER' AS TBL, COUNT(*) AS CNT, 100 AS EXPECTED FROM SUPPLY_CHAIN_HUB.SC_CURATED.XREF_SUPPLIER
UNION ALL SELECT 'XREF_PART', COUNT(*), 500 FROM SUPPLY_CHAIN_HUB.SC_CURATED.XREF_PART
UNION ALL SELECT 'XREF_PLANT', COUNT(*), 20 FROM SUPPLY_CHAIN_HUB.SC_CURATED.XREF_PLANT;

-- KPI validation (CRITICAL - all 7 must match)
-- Expected:
--   KPI-DOI-001  = 9.42  DAYS
--   KPI-FR-001   = 79.82 PERCENT
--   KPI-LC-001   = 89.31 USD
--   KPI-OTD-001  = 73.22 PERCENT
--   KPI-OTIF-001 = 43.95 PERCENT
--   KPI-POR-001  = 42.46 PERCENT
--   KPI-SOT-001  = 46.07 PERCENT
SELECT KPI_ID, KPI_NAME, ROUND(KPI_VALUE, 2) AS KPI_VALUE, UNIT
FROM SUPPLY_CHAIN_HUB.SC_SEM.SEM_KPI_SUMMARY
ORDER BY KPI_ID;
